[COC-60] Added entities
Alaple/CocinArte pull request #14
Opened 2021-10-10 18:00 UTC by Alaple

# Description

We added the entities using the Class diagram

2021-10-12 01:14 UTC, JonathanJusid commented on app/src/main/java/com/bifrost/cocinarte/entities/User.kt
> +    fun delteUser(user: User){
"delteUser" - Debería ser delEte

2021-10-12 22:47 UTC, Alaple commented on app/src/main/java/com/bifrost/cocinarte/entities/User.kt
> +    fun delteUser(user: User){
Feedback aplicado! Muchas gracias!

2021-10-13 23:32 UTC, manuelfalonso commented
Es un bello PR! :D

2021-10-13 23:49 UTC, JonathanJusid approved these changes
Ok!

2021-10-13 23:50 UTC, marianofidalgo approved these changes

2021-10-13 23:52 UTC, marianofidalgo approved these changes

2021-10-14 00:30 UTC, manuelfalonso requested changes
Ahi deje algunos comentarios y tengo una consulta. Por que no son todas parcelable y copy paste de las entities que paso el profe?

2021-10-14 00:30 UTC, manuelfalonso commented on app/src/main/java/com/bifrost/cocinarte/entities/Favorite.kt
> +class Favorite (fav_id: String)
No faltan llaves aca?

2021-10-14 00:30 UTC, manuelfalonso commented on app/src/main/java/com/bifrost/cocinarte/entities/User.kt
> +        reward: Array<Reward>,
no tineen que ser MutableList?

2021-10-14 00:30 UTC, manuelfalonso commented on app/src/main/java/com/bifrost/cocinarte/entities/User.kt
> +
Todo los campos recibidos en la clase no tienen que estar aca? y tambien en el init? aunque sean inicializados con null?

2021-10-14 00:30 UTC, manuelfalonso commented on app/src/main/java/com/bifrost/cocinarte/entities/Recipe.kt
> +    yield: Int,
yield parece palabra reservada. no arroja error?

2021-10-14 01:23 UTC, Alaple commented on app/src/main/java/com/bifrost/cocinarte/entities/User.kt
> +        reward: Array<Reward>,
Aplicado feedback! Thanks!

2021-10-14 01:23 UTC, Alaple commented on app/src/main/java/com/bifrost/cocinarte/entities/User.kt
> +
Aplicado feedback! Thanks!

2021-10-14 01:23 UTC, Alaple commented on app/src/main/java/com/bifrost/cocinarte/entities/Recipe.kt
> +    yield: Int,
Aplicado feedback! Thanks!

2021-10-14 01:23 UTC, Alaple commented on app/src/main/java/com/bifrost/cocinarte/entities/Favorite.kt
> +class Favorite (fav_id: String)
Aplicado feedback! Thanks!

2021-10-14 01:26 UTC, manuelfalonso approved these changes
lgtm
![image](https://user-images.githubusercontent.com/52722318/137234929-e3501af8-3a8a-4de1-8db2-30c5dc13a47f.png)

2021-10-14 01:30 UTC, merged