Coc 71 home
Alaple/CocinArte pull request #18
Opened 2021-10-15 00:45 UTC by marianofidalgo

2021-10-15 21:48 UTC, manuelfalonso requested changes
Viendo la estructura de las carpetas del proyecto falta un rebase para estar actualizado con Develop

2021-10-15 21:51 UTC, Alaple requested changes
The Home page is not complete, no recipe cards are being displayed

![image](https://user-images.githubusercontent.com/34112271/137557435-ff025dea-dfaa-4d77-84e3-51235df92ed8.png)

2021-10-25 01:06 UTC, Alaple approved these changes
Me gusto mucho el ultimo commit, un capo ese pibe

2021-10-25 01:12 UTC, manuelfalonso approved these changes
lgtm :)

2021-10-25 01:23 UTC, merged