[COC-67] Se creo PreferenceFragment y se corrigio el id de RegisterFragment.
Alaple/CocinArte pull request #22
Opened 2021-10-18 23:06 UTC by marianofidalgo

2021-10-18 23:41 UTC, Alaple requested changes
Cant see your changes on the app. Please change the navigation or apply your changes to the corresponding files.

![image](https://user-images.githubusercontent.com/34112271/137820868-e5d324e1-e55d-4c26-a077-3998363c1c62.png)

2021-10-18 23:43 UTC, manuelfalonso commented
Ya existe un Activity para Preferences. activities -> PreferenceActivity. Habria que utilizar ese usando de guia el proyecto SettingsExample del profe

2021-10-25 01:11 UTC, Alaple approved these changes
![image](https://user-images.githubusercontent.com/34112271/138620768-ec4992c3-3d42-454a-a69a-ae51653340eb.png)

2021-10-25 22:11 UTC, julianalvarezkusy approved these changes
Looks good!

2021-10-25 22:53 UTC, merged

2021-10-25 22:53 UTC, Alaple approved these changes
LGTM