[COC-103] User profile backend
Alaple/CocinArte pull request #40
Opened 2021-11-04 04:02 UTC by manuelfalonso

## Se cargan los datos del nombre y nivel en el Perfil
![image](https://user-images.githubusercontent.com/52722318/140255826-fa38145c-613a-4f65-94be-8d7752e5fb32.png)

## La button bar se ajusta segun si el usuario esta logueado o no:
![image](https://user-images.githubusercontent.com/52722318/140255734-644d0956-bcba-4642-b7d7-bdff31b41f7a.png)
![image](https://user-images.githubusercontent.com/52722318/140255793-8abf5a65-0aae-4770-b28d-85885c614642.png)

2021-11-04 04:05 UTC, manuelfalonso commented
Tambien se tuvieron que modificar las entities User y Preference dado que deben tener un constructor vacio sino Firestore no funciona

2021-11-07 20:48 UTC, julianalvarezkusy requested changes
![image](https://user-images.githubusercontent.com/60948729/140661397-24315a42-4051-4677-a107-473d2db212ec.png)

La app crashea cuando entro al user profile, este es el error:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bifrost.cocinarte, PID: 18595
    java.lang.NullPointerException
        at com.bifrost.cocinarte.models.main.UserProfileViewModel.getUserFirestore$lambda-0(UserProfileViewModel.kt:46)
        at com.bifrost.cocinarte.models.main.UserProfileViewModel.$r8$lambda$VlGjdXquJ-78uywedHACzPAfs5Y(Unknown Source:0)
        at com.bifrost.cocinarte.models.main.UserProfileViewModel$$ExternalSyntheticLambda1.onSuccess(Unknown Source:6)
        at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

2021-11-07 21:43 UTC, julianalvarezkusy approved these changes
Un lujo! 
En otra iteración se podría validar que el user no sea null, así no crashea (no debería igualmente venir vació).

2021-11-07 23:34 UTC, Alaple approved these changes
Lgtm

2021-11-07 23:34 UTC, merged