[COC-56] Account and Profile - Update User
Alaple/CocinArte pull request #53
Opened 2021-11-20 23:02 UTC by Alaple

2021-11-22 21:40 UTC, julianalvarezkusy approved these changes
LGTM!

2021-11-23 00:55 UTC, manuelfalonso requested changes

2021-11-23 00:55 UTC, manuelfalonso commented on app/src/main/java/com/bifrost/cocinarte/fragments/main/AccountProfileFragment.kt
> -            Snackbar.make(rootLayout, "TODO UPDATE", Snackbar.LENGTH_SHORT).show()
Aca volveria agregar el Snackbar. Al hacer click en update no dice ni hace nada.

2021-11-23 01:25 UTC, Alaple commented on app/src/main/java/com/bifrost/cocinarte/fragments/main/AccountProfileFragment.kt
> -            Snackbar.make(rootLayout, "TODO UPDATE", Snackbar.LENGTH_SHORT).show()
Feedback applied

2021-11-23 01:31 UTC, manuelfalonso approved these changes
lgtm

2021-11-23 01:35 UTC, merged