[COC-104] Reset Password Dialog
Alaple/CocinArte pull request #54
Opened 2021-11-21 00:10 UTC by Alaple

2021-11-22 21:48 UTC, julianalvarezkusy approved these changes
LGTM!

2021-11-23 00:47 UTC, manuelfalonso requested changes
![image](https://user-images.githubusercontent.com/52722318/142955959-b5115783-139e-48e1-88af-6654d0aee8fa.png)

2021-11-23 00:58 UTC, manuelfalonso commented on app/src/main/java/com/bifrost/cocinarte/dialogs/ResetPasswordDialogFragment.kt
> +                                ResetPasswordFragmentDirections.actionResetPasswordFragmentToResetEmailSentFragment2()
creo que el problema esta aca

2021-11-23 01:50 UTC, manuelfalonso approved these changes
lgtm

2021-11-23 01:50 UTC, merged