Pantallas Register y Started
Alaple/CocinArte pull request #6
Opened 2021-09-30 03:50 UTC by marianofidalgo

Me base en la pantalla de login

2021-09-30 13:14 UTC, manuelfalonso commented
Hola Marian! ayer justo estuvimos hablando con el profesor para ver como encarar el tp de la forma mas ordenada posible y nos recomendo hacer toda la navegacion base (con los fragments vacios) y las entities/clases bases que vamos a necesitar. Esto el viernes igual lo hablamos. 
Que alguien me corrija pero entiendo que en TODO el proyecto tiene que haber solo dos activities y dos navgraph. Entonces los archivos que marque con una cruz no serian necesarios. Si tienen codigo que escribiste vos, deberias sacarlo y ponerlo en los fragments y dsp borrar esos archivos. avisen cualquier cosa
![image](https://user-images.githubusercontent.com/52722318/135461477-0a011d9b-5501-478d-bbbe-c92d60272770.png)

2021-09-30 13:21 UTC, manuelfalonso commented
me olvide que podia ver el codigo.. Vi en los "Files changed" y creo que podria borrar esos archivos sin problemas. avisa cualquier cosa y vemos que dice el resto

2021-10-01 01:19 UTC, Alaple requested changes
Omitiendo el problema de los Activiy el register se ve bien. Fijate si podes darle un poco de espacio como esta en el mock.

![image](https://user-images.githubusercontent.com/34112271/135551101-dc8bb791-53ed-4fc1-9f5d-933632658aa4.png)

2021-10-01 01:19 UTC, Alaple commented on app/src/main/java/com/bifrost/cocinarte/activities/RegisterActivity.kt
> +package com.bifrost.cocinarte.activities
Solo tenemos que tener dos activity en todo el proyecto. El LoginActivity y el Main.  Porfavor eliminar este activiy

2021-10-01 01:19 UTC, Alaple commented on app/src/main/java/com/bifrost/cocinarte/activities/StartedActivity.kt
> +package com.bifrost.cocinarte.activities
Solo tenemos que tener dos activity en todo el proyecto. El LoginActivity y el Main.  Porfavor eliminar estos activiy

2021-10-01 19:15 UTC, manuelfalonso commented
> Omitiendo el problema de los Activiy el register se ve bien. Fijate si podes darle un poco de espacio como esta en el mock. Lo mismo con el getStart el espaciado si podes.
> 
> ![image](https://user-images.githubusercontent.com/34112271/135551101-dc8bb791-53ed-4fc1-9f5d-933632658aa4.png)

El login lo hice muy parecido a ese para que el teclado del cel no te tape el boton de register/log in. Cuando lo ves sin el teclado parece como que sobra un monton de lugar pero si lo ves con el emulador queda perfecto. 
Si lo decis por los otros espacios entre textos puede ser que esten un toque separados

2021-10-04 20:26 UTC, marianofidalgo commented
![image](https://user-images.githubusercontent.com/62575541/135919763-c99f7826-e4c6-494b-8498-849b47ecb7ce.png)
![image](https://user-images.githubusercontent.com/62575541/135919835-dd8e898a-a13e-4905-992e-d814a0a61541.png)

2021-10-05 00:31 UTC, Alaple approved these changes
![giphy](https://user-images.githubusercontent.com/34112271/135942189-5daa7b14-cfa3-4359-a059-5e71e6028d73.gif)

2021-10-05 00:33 UTC, JonathanJusid approved these changes
Good job!

2021-10-05 00:33 UTC, merged