[COC-27] Added gogole serivice file to conect with Firebase
Alaple/CocinArte pull request #9
Opened 2021-10-03 20:46 UTC by Alaple

# Description

We added the google service files to connect with FireBase DB

2021-10-07 16:16 UTC, julianalvarezkusy approved these changes

2021-10-07 20:25 UTC, manuelfalonso reviewed
Intente instanciar la base de datos como esta en el proyecto del profe y no me deja. Me dice que falta una librería.
Tal vez con las nuevas librerías funciona diferente. Pero habría que ver la documentación porque no vamos a poder hacer copy paste del profe.

![image](https://user-images.githubusercontent.com/52722318/136456772-9875bc0f-a9da-46fd-8bd5-c8023881d991.png)

2021-10-08 22:19 UTC, manuelfalonso requested changes
https://github.com/Alaple/CocinArte/pull/9#pullrequestreview-774357555

2021-10-09 19:02 UTC, manuelfalonso requested changes

2021-10-09 19:02 UTC, manuelfalonso commented on app/build.gradle
> +    implementation 'com.google.firebase:firebase-analytics-ktx'
Veo que agregaste analiticas pero entiendo que sigue faltando la base de datos Firestore.
Probaste la siguiente linea en algun fragment a ver si funciona?
val db = Firebase.firestore

Para implementar Firestore
    // Firestore
    implementation 'com.google.firebase:firebase-firestore-ktx:21.4.3'

2021-10-09 19:11 UTC, manuelfalonso commented on app/build.gradle
> +    implementation 'com.google.firebase:firebase-analytics-ktx'
https://firebase.google.com/docs/firestore/quickstart?authuser=0

2021-10-10 17:22 UTC, Alaple commented on app/build.gradle
> +    implementation 'com.google.firebase:firebase-analytics-ktx'
Resuelto Manu! Gracias por el feedback!

2021-10-10 20:14 UTC, manuelfalonso approved these changes
Lgtm

2021-10-10 23:27 UTC, merged